### ISSUE TITLE
Sprite broken of Shiny Vanhite Falinks 

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#1985] opened 2022-11-18 02:46 UTC
The Sprite of the Shiny Vanhite Falinks does not exist, and that make a broken texture in the Poketracker

![image](https://user-images.githubusercontent.com/108286828/202605048-ef380331-6951-46ac-b8fc-6351402321af.png)
![image](https://user-images.githubusercontent.com/108286828/202605090-15c9088c-9405-4ad3-ab74-1118daa4a08e.png)

**Comment by StrideMate** [comment] 2023-01-26 12:43
This has since been fixed, I've tested the sprite and it seems it has it's texture and works as intended! Thank you for the report and if you happen to come upon this issue or any other issue please do let us know! Closing! 

![2023-01-26_23 42 10](https://user-images.githubusercontent.com/78794976/214838878-939d4556-1234-48df-a200-f79ce3fa550a.png)

![2023-01-26_23 44 30](https://user-images.githubusercontent.com/78794976/214838886-6a04f52e-4a74-4214-a857-d26f2ae8c16e.png)

**Closed as completed by StrideMate** 2023-01-26 12:43 UTC
