### ISSUE TITLE
[Water Float Decoration] They can be placed in admin claims such as spawn

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2376] opened 2024-02-09 02:04 UTC
**Describe the bug**
I logged in to see a water float randomly placed in spawn. I went and bought one of my own and respecting claims was also able to place them in spawn. I tried all of the other decorations from warp market and the water floats are the only ones that work this way.
**To Reproduce**
1. Go to warp market
2. Get yourself a water float of any color
3. Go to an admin claimed area and place away

**Expected behavior**
Items should not be able to be placed anywhere from any player in admin claims

**Username: _Peyton_7**

**Server name: FunPolice (all applicable):**

**Comment by Peyton7** [comment] 2024-02-09 02:06
This also applies for item frames and paintings in the end but I believe i made a separate ticket for that some time ago. Same thing, with the water float in the end. Only the water float decoration can be placed

**Comment by Rasgnarok** [comment] 2024-02-25 18:46
I think this is likely a missing GD flag, @chefburne or @WisconsinWinters

**Comment by Rasgnarok** [comment] 2024-02-29 06:18
Duplicate of https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/2288

**Closed as completed by Rasgnarok** 2024-02-29 06:18 UTC
Labels: bug, griefdefender
