### ISSUE TITLE
Forced Spawn Legends not Spawning in Correct Time Frames.

### ISSUE THREAD

**Issue by kdy99** [ObliqueNetwork/Terra#2372] opened 2024-02-02 17:18 UTC
Players have been using there shards for instance to spawn a Zamenzenta at night and are getting a zacian spawn which is a daytime spawn also had the same issue with Zekrom/Reshiram etc.

To reproduce attempt just force spawning a legend using the shards for a specific legend Day/Night and find the corresponding spawn not being correct. 

https://outplayed.tv/media/eXnrrn

Across all servers.

Expected behavior should be spawns should be spawning in correct time frames when attempted to be force spawned for players.

**Comment by Rasgnarok** [comment] 2024-02-25 18:53
We've added some debug commands to force more information on these issues, this is a duplicate of the original issue which is already being investigated. Thanks!

**Closed as completed by Rasgnarok** 2024-02-25 18:53 UTC
Labels: duplicate
