### ISSUE TITLE
[DexRank] One Time Rewards - Luxury

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1869] opened 2022-09-18 20:27 UTC
The one time rewards for ranking up to luxury rank fails to disperse all items, its missing:
6x Golden hour glass
1x Specific Max IV Mod

1. Achieve 40% Dex completion
2. Redeem rank in /dexrewards
3. Observe items dispersed
4. notice missing items.

A full kit of all one time rewards to be dispersed without any missing items.

![luxuryRewards](https://user-images.githubusercontent.com/17133410/190926955-3aa0bd4e-9227-4c4d-b7a9-4bbc9d5eea6d.png)

![LuxuryDexrank](https://user-images.githubusercontent.com/17133410/190926902-9b0d66bc-4033-4e24-ab7c-d1f2f3530abf.png)

Player has already been compensated for issue.

**Comment by KittyKatzyn** [comment] 2022-09-24 04:51
I have fixed the hourglass issues for Great, Ultra, and Luxury - am still investigating the IV mod issue :)

**Comment by KittyKatzyn** [comment] 2022-09-27 05:40
Having looked into this further, I cannot reproduce the issue of the dex rank not giving the modifier.  It is true that it did not announce giving me the modifier in chat, but the item itself was present in my inventory, and useable. :)  I have also tested other dex ranks, and found they work as well.

Closing!

**Closed as completed by KittyKatzyn** 2022-09-27 05:40 UTC
Labels: bug, needs testing, spigot
