### ISSUE TITLE
[Particles] After applying particles to a desired pokemon the particles will not appear.

### ISSUE THREAD

**Issue by Peyton7** [ObliqueNetwork/Terra#2389] opened 2024-02-25 05:10 UTC
**Describe the bug**
Particles applied to pokemon do not work/show up. Any pokemon tested by Cpt where he applied the particles to them, none of the particles appeared. Other players claim that their pokemon that had particles no longer have them.

**To Reproduce**
1. On any live server give yourself any aura particles
2. Apply the particles to a pokemon
3. See the missing particle effects

**Expected behavior**
An aura of the specified particles should be around the chosen pokemon

**Username: _Peyton_7**

**Server name (all applicable): FunPolice**

**Comment by WisconsinWinters** [comment] 2024-02-25 05:25
what else are you doing with pokemon, putting them in/out of pcs, disconnecting/reconnecting, video settings etc?

**Comment by Rasgnarok** [comment] 2024-02-25 18:34
Needs more information, we're receiving tickets saying the particles returned after a server restart. Can this please be tested a bit more - ideally with different cases on beta with restarts?

**Comment by G59Rhett** [comment] 2024-02-25 19:04
Issue was reported again on 2/24/24 at 9:09 pm CST 
Player Dodgethekidd
Server Titan

Player Dodgethekidd used the rotating spiral particles on a shiny aerodactyl that seemingly did not apply, yet took the particles from him. He then made a ticket about them not working, To which the player was told to wait until server restart to see if the particles appeared after restart. Upon the server restarting the particles DID show up and are now working as intended.  As far as why they did not work to begin with we could not figure out.

Player could not give anymore information as to how this occured when asked.

**Comment by G59Rhett** [comment] 2024-02-25 19:06
I would also like to mention it seems as if sometimes the server restarts with NO particles working and then other times when it restarts they will be working as if the plug in sometimes fails to load properly. Due to when one person reports the particles not working they will not work for any other player on the effected server.

**Comment by WisconsinWinters** [comment] 2024-02-29 06:15
would you have some dates where particles didn't load at all/were wiped? i can check logs to see if it failed loading

**Comment by WisconsinWinters** [comment] 2024-06-08 06:17
no further reports of this/unable to reproduce, closing.

**Closed as completed by WisconsinWinters** 2024-06-08 06:17 UTC
Labels: missing info
