### ISSUE TITLE
Remove aggro pokemon in vanha. Breaks quests/gyms

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2352] opened 2024-01-10 22:52 UTC
**Describe the bug**
Aggro pokemon can attack players in vanha after they done a quest or prepping for a gym and then they could break each other.
For Quests, The said quest after being attacked won't work then you'd either have to relog or get fixed
For gyms, People can be waiting for the gym leader to ready there team, and then it will get rid of the gui/ and then gym leader will be stuck in gui. 

**To Reproduce**
1. Go to Vanha 
2. go do a quest after dialogue get attacked from pokemon 
3. quest broken for u :( (same for gyms)

**Expected behavior**
Aggro be off everything will work well WEEEEEEEEE

(can explain more if needed)

**Comment by WisconsinWinters** [comment] 2024-01-11 23:12
how specifically is it breaking gyms and quests? as in stopping progression on quests?

**Comment by ShapooK** [comment] 2024-01-11 23:14
Yes it stops quest progression, like people won't be able to do anything can't challenge no boss or anything and have to restart game i believe and sometimes it wouldn't work.

**Comment by WisconsinWinters** [comment] 2024-01-11 23:53
how are pokemon breaking the gyms? i dont believe pokemon spawn at all in gym builds

**Comment by WisconsinWinters** [comment] 2024-01-12 00:26
Got aggro'd on Vahna during the quest Vahna League during two different stages, and I was able to proceed and fight bosses as normal. Would you happen to have specific quests that do this?

**Comment by ShapooK** [comment] 2024-01-12 00:34
For the gyms I remember someone getting attacked by the pokemon outside of the gym and the mons walking towards the gyms believe it was kuanti one then getting attacked

Vanha league had it happen to me after I was done talking with the lady that gives the shulker. Then got attacked by a pokemon and I couldn’t do any other quest had to force close the game in order to work 

if I remember correctly vanha aggro was gonna get removed and it was agreed it was on a suggestion on disc but then never was disabled

**Comment by Rasgnarok** [comment] 2024-02-25 19:03
If it's not causing issues then I don't see why we would need to remove it, don't seem we can break it as Wis confirms

**Comment by itsAmaze** [comment] 2024-02-25 19:11
although it does not happen as often when im in a gym challenge during team preview screen if i get aggro'd on by a wild pokemon i get stuck and i am unable to do anything

**Comment by Rasgnarok** [comment] 2024-02-29 06:32
We need more information on what exactly happens/how it happens to reproduce, @itsAmaze

**Comment by itsAmaze** [comment] 2024-02-29 06:36
its only happened to me once but from what i remember after i accepted a gym battle and was on team preview i was selecting the order of the mons and before i could click the start button to start the battle a random pokemon aggro'd on me and it put me in battle with the mon and after the battle it would not let me continue the gym challenge and i had to relog

**Comment by WisconsinWinters** [comment] 2024-02-29 07:43
> its only happened to me once but from what i remember after i accepted a gym battle and was on team preview i was selecting the order of the mons and before i could click the start button to start the battle a random pokemon aggro'd on me and it put me in battle with the mon and after the battle it would not let me continue the gym challenge and i had to relog

i just attempted this on beta with many aggressive pokemon spawned around me on the overworld, was not able to be aggressed in either the team select UI or in the pokemon rule select UI

**Comment by Rasgnarok** [comment] 2024-06-09 09:45
Cannot reproduce, closing

**Closed as completed by Rasgnarok** 2024-06-09 09:45 UTC
Labels: missing info
