### ISSUE TITLE
[Crates] Can't Interact With Astral Crate

### ISSUE THREAD

**Issue by Malphir** [ObliqueNetwork/Terra#1833] opened 2022-09-10 03:05 UTC
**Describe the bug**
When trying to interact with the Astral Crate on Titan, nothing happens. Doesn't open, or pull up an interface. This is the same interaction bug that has repeated multiple times for various crates across all servers.

**Username:**
Dracten

**Server name (all applicable):**
Titan

**Comment by MissElyri** [comment] 2022-09-10 04:59
Crates have been fixed and are working as intended. Closing.

**Closed as completed by MissElyri** 2022-09-10 04:59 UTC
