### ISSUE TITLE
Fake out doesnt flinch 

### ISSUE THREAD

**Issue by Dovukin** [ObliqueNetwork/Terra#2161] opened 2023-03-22 17:27 UTC
**Describe the bug**
During a gym battle with a player i used fake out twice which should always flinch the opponent yet both times he didnt flinch , the mons being weavile and garchomp also not having inner focus or any item that would prevent a flinch

**To Reproduce**
1. Go to titan and battle agni
2. Have someone use fake our (on morpeko if youre the gym leader)
3. see issue

**Expected behavior**
Fake out should flinch always

**Screenshots**

**Username:**
Dovukin
**Server name (all applicable):**
Titan

**Additional context**
First time im seeing a bug like this , the flinch just never took into effect letting my opponent hit me even after fake out was used, only seen it on titan so far

**Comment by Dovukin** [comment] 2023-03-22 21:05
Update: flinching isnt taking into affect in any battle ,been tested in orion with fake out and air slash

**Comment by Khrisstias** [comment] 2023-03-25 04:40
This seems to be a nebula only problem, as it works fine in singleplayer and on a multiplayer test server. Forwarding

**Comment by WisconsinWinters** [comment] 2024-06-11 07:08
just attempted and works as intended. closing

**Closed as completed by WisconsinWinters** 2024-06-11 07:08 UTC
Labels: bug, nebulamc, forwarded
