### ISSUE TITLE
[Feature] Game crashes while feeding xp candy to pokemon

### ISSUE THREAD

**Issue by dvos1998** [ObliqueNetwork/Terra#1835] opened 2022-09-11 15:45 UTC
**Describe the bug**
When I was feeding my pachirisu xp candies (don't know if this is important for it but, it's also a shiny with the pick up ability) and alternating between the xp candies (so i don't have to wait for the cooldown on feeding xp candies) the game crashed. I tried it a second time and it crashed again.

**To Reproduce**
1. Have your pokemon out
2. Feed your pokemon xp candies by keeping the feed button pressed
3. While keeping your feed button pressed, scroll to the next xp candy while the other candy is on cooldown
4. Sometimes the crash happens after a few candies, so repeat until it crashes

**Expected behavior**
The expected result is that you can feed your pokemon candies and the game doesn't crash

**Username:**
DomiVos

**Server name (all applicable):**
Titan

**Logs:**
[crash-2022-09-11_17.27.21-client.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9542891/crash-2022-09-11_17.27.21-client.txt)
[crash-2022-09-11_17.29.08-client.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9542892/crash-2022-09-11_17.29.08-client.txt)

**Additional context**
Obviously the problem is probably alternating between the candies and somehow getting a nullpointer as a result.

**Comment by Deathnight7976** [comment] 2023-01-23 01:41
The cause of this used to be scrolling when in the level up menu, and has since been fixed by a pixelmon update. Fixed, Closing.

**Closed as completed by Deathnight7976** 2023-01-23 01:41 UTC
Labels: bug, pixelmon
