### ISSUE TITLE
[NPC's] NPC's fail to distribute pixelmon xp upon defeat

### ISSUE THREAD

**Issue by F4Mx** [ObliqueNetwork/Terra#2057] opened 2023-01-09 01:15 UTC
**Describe the bug**
Majority of trainers in the adventure map dont give exp, only some trainers give exp with 90% of them not giving anything

**To Reproduce**
1. Fight trainer
2. Beat the trainer
3. No exp

**Expected behavior**
When you fight a trainer if you get the popup screen detailing the rules of the battle and letting you choose your pokemon, you wont get exp from the trainer, but if you dont get the popup screen you get the exp from defeating the trainer

**Screenshots**
![image](https://user-images.githubusercontent.com/122241208/211228267-635e50f1-8ef0-4e51-b395-cc59f2e0bd8e.png)
This is the popup screen i mentioned and if you get this when fighting a trainer you dont get any exp

**Username:**
F4M

**Server name (all applicable):**
Orion

**Additional context**

**Comment by fatyg5** [comment] 2023-01-09 01:49
Sounds like a Pixelmon issue, guessing there's something that's marking the trainer battle as PvP (which we have EXP off for), and not as a trainer battle due to that screen (just a guess). Can you test this in SP and if it continues on there report this issue to the Pixelmon forums, please? https://pixelmonmod.com/tracker.php?p=2

**Comment by F4Mx** [comment] 2023-01-09 03:37
I checked singleplayer and it seems to be working fine on there?

**Comment by CenizaRey** [comment] 2023-02-05 18:51
This is not a bug, but a config option, and is an intended feature as of right now. Closing

**Closed as not planned by CenizaRey** 2023-02-05 18:51 UTC
