### ISSUE TITLE
partial cosmetic kits given as reward

### ISSUE THREAD

**Issue by Centuron** [ObliqueNetwork/Terra#1862] opened 2022-09-17 17:53 UTC
**Describe the bug**
I redeemed a solar key at the crate, and was given a cosmetic kit as a reward.  However I was only given a Ball Mod.
The text chat showed that i had received %item% since my inventory was no longer full and was shown this text 3 times.
I also has a couple empty spaces in my hot bar, and bunch of free space in my inventory.
I also want to note, that i also see this whenever I redeem the Vote Crate Keys, however I think this Issue occurs because multiple different Items are given out.

**To Reproduce**
1. Use Solar Crate Key
2. Wait for reward.
3. Reward becomes bugged
![2022-09-17_05 52 49](https://user-images.githubusercontent.com/113794806/190869958-985b871d-2341-4476-bb8f-74d1b17c5804.png)
![2022-09-17_05 54 14](https://user-images.githubusercontent.com/113794806/190869959-e7799d07-b2be-4231-a298-38a7b8b3c9ef.png)

**Expected behavior**
I expected the full cosmetic kit to be given out as long as I has sufficient inventory space, as with other crate keys.

**Screenshots**

**Username:**
Centuron
**Server name (all applicable):**
Titan
**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_
[2022-09-17-1.log.gz](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9592331/2022-09-17-1.log.gz)

**Additional context**
I've attached logs, but i don't know if they will help.

**Comment by MissElyri** [comment] 2022-09-17 22:24
Refunded, Duplicate of #1855 and #1841

**Closed as completed** 2022-09-17 22:26 UTC
