### ISSUE TITLE
/trylevelevo not working properly

### ISSUE THREAD

**Issue by ShapooK** [ObliqueNetwork/Terra#2353] opened 2024-01-10 23:14 UTC
**Describe the bug**
Even though all the requirements have been met with /trylevel evo. The pokemon still won't evolve. even if the pokemon in question doesn't have no held item or anything. 
Pictures below will be the example.

**To Reproduce**
1. Get a high level pokemon that should evolved already
2. do /trylevelevo (slot) on it 
3. Doesn't evolve. 

**Expected behavior**
/trylevelevo should work instantly on the mon that you tried the command on 

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/c82212e7-d33c-44c6-a5e8-c08f2780a65b)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/35164973/f1889b92-f065-48db-9f9e-d34bb032203b)

**Username:**
ShapooK

**Server name (all applicable):**
Titan but all.

**Comment by WisconsinWinters** [comment] 2024-01-11 22:31
Is this without relogging? Currently not able to reproduce, even with a different OT from as from the picture

**Comment by Rasgnarok** [comment] 2024-02-29 06:27
Closing, bug cannot be reproduced.

**Closed as completed by Rasgnarok** 2024-02-29 06:27 UTC
Labels: missing info
