### ISSUE TITLE
Bypass Afk

### ISSUE THREAD

**Issue by MoonEverDark** [ObliqueNetwork/Terra#2312] opened 2023-10-12 13:30 UTC
You can bypass afk by being in the daycare with finished eggs or breeding pair.
Tested with no eggs or breeding pair and does activate afk.

MoonEverDark

Orion

**Comment by WisconsinWinters** [comment] 2023-11-20 06:19
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/39723405/e21b48b0-d7e1-478d-a45c-28bf0bae7d22)

I'm not able to reproduce this, anything else you have been doing?

**Comment by Rasgnarok** [comment] 2024-02-29 06:12
Needs re-testing

**Comment by WisconsinWinters** [comment] 2024-03-22 03:39
still not able to reproduce afterr re-testing, closing

**Closed as completed by WisconsinWinters** 2024-03-22 03:39 UTC
Labels: missing info
