### ISSUE TITLE
pwarp renaming inssufficiant permmision

### ISSUE THREAD

**Issue by redjeff1** [ObliqueNetwork/Terra#1986] opened 2022-11-20 23:00 UTC
**Describe the bug**
whenever you try and rename your pwarp and put the new name in chat you don't have permission to change it

**To Reproduce**
go into pwarp menu
edit your pwarp
change the name
put the name in chat
get denied

**Screenshots**
![image](https://user-images.githubusercontent.com/48700761/202931243-6d0cbfaf-203d-4f8f-b756-5e19514472af.png)

**Username:**
REDJEFF
**Server name (all applicable):**
atlas

**Comment by Deathnight7976** [comment] 2023-01-23 02:18
Closing, Duplicate of #1902

**Closed as completed** 2023-01-23 02:19 UTC
Labels: duplicate
