### ISSUE TITLE
Staff Permissions

### ISSUE THREAD

**Issue by iamcjmxv** [ObliqueNetwork/Terra#2212] opened 2023-07-15 03:35 UTC
**Describe the bug**
Staff Commands Helper through Senior Mod that don't work

**To Reproduce**
***Helper Commands That Don’t work or shouldn’t work***
/tp  ----> is usable on Atlas, titan, orion when shouldn't be
/note -----> Doesnt proc / work atlas, titan, orion     --- UPDATE: Does not exist anymore, no replacement yet
/co i --- needs taken off sheet
/endbattle <player> ----- no perm atlas, titan, orion

***Trial Mod That Don’t work***
/gamemode spectator ---> gamemode perms are nonexist for tmod
/tphere ---> appears red but when completed says no perm
/nickname  ---> works kind of, shows in dms, but not main chat (screenshot below) (same result for moderator)
                   I changed nickname from CptTCovenant to CptCovenant  (Without the extra T, I glance over that T sometimes)

***Moderator That Don’t work***
/removehome (home) (player) ----? does not proc at all
/give ---> doesnt work, no perm
/tphere ---> ELEMENTAL FIXED FOR MOD
/enderchest <player> ----> no perm
/gamemode spectator and survival are the only ones that work, as intended i believe. 

***Senior Moderator That Don’t work***
/gamemode creative —> no perm

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/60482171/c900f32f-4b3b-4e7a-b5cf-cef365d4da78)

**Username:**
_Conj (Was demoted and promoted as testing went though)

**Server name (all applicable):**
All

Did not test  replacement for CMI commands, not on sheet yet.

**Comment by MissElyri** [comment] 2023-07-18 11:38
Also including /tppos for trialmod+ *Unless we're moving it up to Mod+ in lieu of recent events)

**Comment by Rasgnarok** [comment] 2023-07-19 05:52
- /tp ----> is usable on Atlas, titan, orion when shouldn't be
_removed_
- /note -----> Doesnt proc / work atlas, titan, orion --- UPDATE: Does not exist anymore, no replacement yet
_you need to use /warn now, `/warn [-s] <target> <reason> [server:*]` and `/warnings <target>`_
- /co i --- needs taken off sheet 
_why?_
- /endbattle ----- no perm atlas, titan, orion
_Not needed anymore, no waiting bugs left._

- /gamemode spectator ---> gamemode perms are nonexist for tmod
_fixed_
- /tphere ---> appears red but when completed says no perm
_fixed_
- /nickname ---> works kind of, shows in dms, but not main chat (screenshot below) (same result for moderator)
_pending TBA, we have a different nick command_

- /removehome (home) (player) ----? does not proc at all
_should be a srmod perm, now exists for that group_
- /give ---> doesnt work, no perm
_give is not a command for moderators_
- /tphere ---> ELEMENTAL FIXED FOR MOD
_? but it inherits from trialmod_
- /enderchest ----> no perm
_fixed when targeting others_
- /gamemode spectator and survival are the only ones that work, as intended i believe.
_coolio_

- /gamemode creative —> no perm
_pending discussions_

**Comment by iamcjmxv** [comment] 2023-07-19 16:23
> 

Hi,
I got Co I mixed up with cmi whilst writing this post. My bad. Co I is fine.

**Comment by WisconsinWinters** [comment] 2024-03-16 01:31
all staff perms updated a while ago, closing

**Closed as completed by WisconsinWinters** 2024-03-16 01:31 UTC
