### ISSUE TITLE
Atumnal Event pokes missing texture and sprites. 

### ISSUE THREAD

**Issue by EzelBerbier** [ObliqueNetwork/Terra#2036] opened 2022-12-23 06:48 UTC
In the 1.4.0 version of the texture pack, Eclipse Cresselia does not have the sprite and the texture model. I don't have the eclipse Darkrai, so I don't know if have the same issue.

![image](https://user-images.githubusercontent.com/108286828/209286327-58005169-821e-48d9-8116-f8d1fd6e34d4.png)
![image](https://user-images.githubusercontent.com/108286828/209286386-c69f59c6-b0c7-401a-9899-3af6bc9e096c.png)

**Comment by EzelBerbier** [comment] 2022-12-23 06:52
I want to add that Autumnal Forms are missing too (Zarude as an example). I checked Autumnal Ursaluna, Tsareena, Liligant and Ludicolo and all of them are missing. I dont have the leafeon, celebi and gardevour autumnal form, so i can't confirm, but could be the same.

![image](https://user-images.githubusercontent.com/108286828/209286575-7e740918-d041-4dcd-a6ae-94995687ff36.png)
![image](https://user-images.githubusercontent.com/108286828/209286620-56eed982-0aa2-4c08-9d5e-0564b73f9119.png)

**Comment by CenizaRey** [comment] 2022-12-23 06:58
This is fixed with the next upcoming version of the resource pack

**Comment by CenizaRey** [comment] 2022-12-23 07:02
Closing due to being a duplicate of issue 2008

**Closed as completed by CenizaRey** 2022-12-23 07:02 UTC
Labels: bug, duplicate, nebulamc
