### ISSUE TITLE
Drowning bug [Feature] Bug explanation

### ISSUE THREAD

**Issue by Tybomb12** [ObliqueNetwork/Terra#2364] opened 2024-01-22 06:15 UTC
Well i am curently in the ocean and im not loosing and of the bubbles at all im not sure if this is s bug or my game is lagging just thought you guys shoukd no about it.

**Expected behavior**
to drown and take damage 

**Screenshots**

*Narcia_**

**Server name titan

**Comment by WisconsinWinters** [comment] 2024-02-24 00:36
can't reproduce this, do you ahve any videos or ranks that might be giving you god?

**Comment by Rasgnarok** [comment] 2024-02-29 06:32
Could not be reproduced, closing.

**Closed as completed by Rasgnarok** 2024-02-29 06:32 UTC
Labels: missing info
