### ISSUE TITLE
/skullcollection takes extra heads

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNetwork/Terra#2025] opened 2022-12-19 06:28 UTC
When you redeem a pokemon from /skullcollection, it takes *all* heads for that event. 
I don't have a screenshot, but had extra A G L heads unstacked in my inventory, underneath the ANGEL set required for redemption. 
Much like this ticket https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/1989 
 - don't need refund -
 
**To Reproduce**
Have a set of ANGEL heads and any amount extra unstacked and run /skullcollection
Pick a pokemon
see error

Known on Orion, imagine all servers.

**Comment by Deathnight7976** [comment] 2023-01-23 03:24
Duplicate of #1989

**Closed as completed by Deathnight7976** 2023-01-23 03:24 UTC
Labels: duplicate
