### ISSUE TITLE
In game chat doesn't show in Network-Chat on discord if you include " anywhere in the sentence

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#2137] opened 2023-03-06 04:19 UTC
Hard to provide logs when it doesn't show up.

But if you include " anywhere in your sentence, even connected to other words it will not show up in the discord Network-Chat at all.

**Comment by Deathnight7976** [comment] 2023-03-06 19:42
Duplicate of https://github.com/NebulaMC-GG/Bugs-and-Issues/issues/1971

**Closed as completed by Deathnight7976** 2023-03-06 19:42 UTC
Labels: duplicate
