### ISSUE TITLE
[EventWorld] /wiki

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2082] opened 2023-01-20 18:27 UTC
Using '/wiki <mon>' on Titan in the event world results in no information being displayed. However, on Atlas/Orion the command functions as normal within the event world. Unknown which way its meant to be as it could be meant to be disabled in case of the Trivia event but either way somethings broken.

1. Visit `/titan`
2. Teleport to `/warp sumo|trivia|etc.`
3. Use `/wiki <mon>`
4. Visit `/orion|/atlas`
5. Teleport to `/warp sumo|trivia|etc.`
6.  Use `/wiki <mon>`
7. See error.

Either for `/wiki` not to function in the event world on all 3 servers or for it to function as normal in all 3 servers.

Titan?
Orion/Atlas?

**Comment by WisconsinWinters** [comment] 2024-06-11 06:53
just tested wiki with a couple of party mons, and it is working as intended, closing unless issue appears, and since many events are now moved to event server instead of event world.

**Closed as completed by WisconsinWinters** 2024-06-11 06:53 UTC
Labels: bug, needs testing, nebulamc, migrate
