### ISSUE TITLE
[Custom Pokemons] Icon/Image bugs

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#2116] opened 2023-02-15 21:56 UTC
Some of the custom pokemon images bug out within both GUI's and PCs/Inventory. It will either pick a random texture of different GUI icons or the pokemon directly above it. 

1. Give yourself an Iron Jet, Primal Kyogre, or Primal Arceus (Note this bug occurs after some time and on initial launch will not be there)
2. Check your inventory/party gui
3. See error

For the sprites to always appear properly
![PartyGUI](https://user-images.githubusercontent.com/17133410/219177785-68d8b665-f2e4-4170-a157-572c0dbbca59.png)
![Inventory GUI](https://user-images.githubusercontent.com/17133410/219177805-c59b7f76-0504-4495-a076-9bc491e42ae9.png)

Orion Likely all

This seems to occur after sending the pokemon out. and retrieving it?

**Comment by KittyKatzyn** [comment] 2023-03-01 03:23
We've figured out that this was caused by an outdated Journey,Maps, and was fixed by updating!  Closing!

**Closed as completed by KittyKatzyn** 2023-03-01 03:23 UTC
